# Site settings
title: Jason's Dev Blog
header-img: img/virginisland.jpg
email: jasonkwong11@gmail.com
copyright_name: jasonkwong11
description: > # this means to ignore newlines until "baseurl:"
  The Notes of a Javascript and Rails Developer!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jasonkwongish
github_username:  jasonkwong11
email_username: jasonkwong11@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
